### ISSUE TITLE
Missign translations

### ISSUE THREAD

**Issue by cristinnaiulia** [ahmedkaludi/check-email#10]
The string ”Note” can not be translated, use __(‘Note’, ‘textdomain’) or similar.
https://plugins.trac.wordpress.org/browser/check-email/tags/1.0.1/include/Core/UI/Setting/Check_Email_Core_Setting.php#L197

**Comment by andyluak** [comment]
![image](https://user-images.githubusercontent.com/49715292/119961655-fa54ac80-bfae-11eb-8239-b0b4fe128772.png)
Note appears in the po file
