### ISSUE TITLE
Login OAuth Broken After Updating Check-Email Plugin to 2.0.2

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/check-email#108]
multiple user reported this issue,"The update to 2.0.2 broke the login OAuth process using plugin https://wordpress.org/plugins/wild-apricot-login/.

[27-Sep-2024 17:10:34 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getAccessToken() on null in /home/customer/www/fortcollinscreatorhub.org/public_html/wp-content/plugins/check-email/include/Core/Auth.php:140
Stack trace:
#0 /home/customer/www/fortcollinscreatorhub.org/public_html/wp-content/plugins/check-email/include/Core/Auth.php(344): CheckEmail\Core\Auth->obtain_access_token()
"
Reference Ticket: https://wordpress.org/support/topic/2-0-2-exception-breaks-wild-apricot-login/

**Comment by askcode21** [comment]
same concern: https://wordpress.org/support/topic/support-request-fatal-error-with-ver-2-0-2/

**Comment by swarren** [comment]
Do you have any idea when 2.0.3 will be released? It seems sooner would be better, since it will apparently fix this bug. Thanks.

**Comment by Sanjeevsetu** [comment]
Hi @swarren 

Yes, We are going to released it by next week. Could you confirm us the fix. Just download zip from https://github.com/ahmedkaludi/check-email/tree/2.0.3 and test it.?

**Comment by kumawatvikas** [comment]
Hi @swarren 

Thankyou for feedback.

Please test again same branch as we have committed new codes.

**Comment by swarren** [comment]
Looks like the latest version (unreleased branch) works OK on our staging site.

**Comment by Sanjeevsetu** [comment]
Hi @swarren 

We have pushed an update version 2.0.3 with this fix and now closing this ticket.
