### ISSUE TITLE
Check & Log Email - Email Logs Show Failure as Success

### ISSUE THREAD

**Issue by DavidhCLF** [ahmedkaludi/check-email#113]
**Describe the bug**
In Check & Log Email / Email Logs / Export Logs - when Email Logs status = "Failure" are exported the csv file shows the status mislabelled as "Success"
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Sanjeevsetu** [comment]
Hi @DavidhCLF 

We have fixed this issue and have released new version 2.0.3. Please update to that and test it once.
