### ISSUE TITLE
 Manually woocommerce status change – no log

### ISSUE THREAD

**Issue by mplusb** [ahmedkaludi/check-email#15]
This is issue is widespread (also with other similar plugins). It appears that it is not able to log emails from manually crons via woocommerces. For example if you change an order’s status to completed, it won’t log the sent out emails, while they are sent via phpmailer.
https://wordpress.org/support/topic/manually-woocommerce-status-change-no-log/

**Comment by Sanjeevsetu** [comment]
Hi @mplusb 

Its been long time but I would like to ask you if You still have this issue?? If so, Please create a new tickets with more details or contact us. I am closing this ticket.
