### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by mplusb** [ahmedkaludi/check-email#23]
I just tried to check and I got a 404 error :

“The requested document was not found on this server.”

I’m using WP 5.6.1 and Astra Pro. The settings detected by the plugin are as follows ::

SendMail path (UNIX): /usr/sbin/sendmail -t -i
SMTP server (Windows): localhost
SMTP port (Windows): 25
Add X header:

If this behavior demonstrates that my WP installation is unable to send mail (which I suspect), I’m OK. But this result is unclear.

https://wordpress.org/support/topic/error-404-when-checking/

**Comment by giucu91** [comment]
duplicate #21
