### ISSUE TITLE
Show "from" field in email log

### ISSUE THREAD

**Issue by cristianraiber** [ahmedkaludi/check-email#24]
![image](https://user-images.githubusercontent.com/7841556/113998810-174be980-9862-11eb-98ac-a9d9504afc5b.png)

**Comment by andyluak** [comment]
![image](https://user-images.githubusercontent.com/49715292/120136127-5bac9380-c1da-11eb-98b2-9da8edb35420.png)

**Comment by andyluak** [comment]
Checked with live server , and it works. Closed
