### ISSUE TITLE
Print feature

### ISSUE THREAD

**Issue by beatricelucaci** [ahmedkaludi/check-email#34]
One feature I needed recently was to print an email that was not getting to a recipient.
I was able to use the Email Cop plugin to do this, but that only works when it is blocking emails.
Can you incorporate a feature to display the email into your plugin?

More detail: It looks like the Email Cop plugin creates a post of type wp_email_cop so the page for an email also has a permalink that can be used to display the email as a webpage.

https://wordpress.org/support/topic/print-feature/

**Comment by kumawatvikas** [comment]
Hi, @beatricelucaci 

We already have this functionality of print emails , when you click on view content->preview content as html

https://prnt.sc/hilBxK-aw2O5
let us know is it helpful to you.

**Comment by Sanjeevsetu** [comment]
Hi @beatricelucaci 

Please contact our support, If you need more help on it. https://check-email.tech/contact/
