### ISSUE TITLE
Move the "check email" functionality inside a tab

### ISSUE THREAD

**Issue by cristianraiber** [ahmedkaludi/check-email#44]
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/7841556/157745316-6de68823-df90-4b82-8ad5-5e2da6be6904.png">

---

This should be the "default" view when installing Check Email. We need to move the "Status" functionality inside a tab in the above view.

**Comment by Sanjeevsetu** [comment]
@cristianraiber 

We have made some changes and that might fulfill this ticket's requirement. Please try our latest version and know us your suggestion.
