### ISSUE TITLE
Causes HTML emails to be sent as plain text

### ISSUE THREAD

**Issue by beatricelucaci** [ahmedkaludi/check-email#50]
**Describe the bug**
Multiple plugins may send HTML email notifications but I experienced this issue consistently with HTML emails sent from Gravity Forms and from WPMU DEV Defender Pro weekly notification emails.

When this plugin is active, the emails come through looking like HTML converted to plain text, but I think they’re technically still text/html content type. When I view these emails in your plugin’s logged emails viewer, they render properly, but the emails actually sent by the website are not rendered properly.

I experienced this issue on multiple websites at different web hosts that use different email sending services.

When this plugin is deactivated, the issue is no more.

https://wordpress.org/support/topic/causes-html-emails-to-be-sent-as-plain-text/

**Comment by lucasvlc** [comment]
It happens the same in my installation. I have deactivated your plugin for the moment.

**Comment by razvanaldea89** [comment]
Need more info on this as we can't replicate the issue. A list with active plugins and theme would be noice. Also, server type and PHP version would help.

**Comment by cliffordp** [comment]
I cannot provide this, as it happened on multiple sites and disabling this plugin solved the issue on all the sites so I stopped using this plugin on all my sites. Another user on the .org thread said they experienced it as well so maybe ask them.

**Comment by toktor** [comment]
Also reporting this issue. Disabling the plugin resolved the issue.

We did have "force from email" checked in the plugin.
I can try to debug the issue if you let me know what kind of information you need.

**Comment by Sanjeevsetu** [comment]
Hi @cliffordp, @toktor, @lucasvlc, @beatricelucaci 

We are unable to replicate the issue. If You are still facing the issue, just contact our support https://check-email.tech/contact/.
