### ISSUE TITLE
Parse error after recent update

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/check-email#73]
It throws an error after recent versioon update i.e. 1.0.12
PHP message: PHP Parse error: syntax error, unexpected ')' in /home/337191.cloudwaysapps.com/rsghxmxedh/public_html/wp-content/plugins/check-email/include/Core/UI/Page/Check_Email_Settings_Page.php on line 186\n',

Reference user -: https://magazine3.in/conversation/279381?folder_id=23

**Comment by Sanjeevsetu** [comment]
This issue has been fixed and pushed in v 1.0.12.1
