### ISSUE TITLE
Lates Release 1.0.12.1 crashes WorpPress

### ISSUE THREAD

**Issue by bradkf** [ahmedkaludi/check-email#75]
**Describe the bug**
The latest Update of Plugin (1.0.12.1, released 29 May )  crashed our site. 

**To Reproduce**
Go to site: www.kumoflow.co.za
See the site is broken
Can't login with any user
Can't browse
![image](https://github.com/ahmedkaludi/check-email/assets/68549218/2cca4414-fa73-4229-ba47-564d502578c5)
Can't list users in CLU with: wp user list. Get the same error as emailed. 

**Expected behavior**
Site should be working

**Screenshots**
Errors were received indicating an issue with plugin. 
![image](https://github.com/ahmedkaludi/check-email/assets/68549218/ed7a4a7a-f07d-439d-b4e5-9f94a8dc5116)

**Additional context**

**Comment by Sanjeevsetu** [comment]
Hi @bradkf 

The same issue came in v1.0.12 and fixed in v1.0.12.1. There might be cache at your end. Please check it again or try fresh installation of plugin from wp.org

**Comment by bradkf** [comment]
@Sanjeevsetu thanks!
