### ISSUE TITLE
Images folder missing for jquery-ui.min.css

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/check-email#93]
one user reported this ,"into /check-email/assets/vendor/jquery-ui/themes/base/jquery-ui.min.css file there’s references to an images folder (ex. “.ui-icon{background-image:url(“images/ui-icons_444444_256x240.png”)}” but images folder doesn’t exist. I fixed with a simple upload direclty from https://jqueryui.com/download/#!version=1.12.1 (base theme)."

reference ticket: https://wordpress.org/support/topic/images-folder-missing-for-jquery-ui-min-css/

**Comment by kumawatvikas** [comment]
Ref:- https://github.com/ahmedkaludi/check-email/commit/cb4f5f468e69307045665d0183017e53cdda02a0
